name: Deploy
on:
  push:
    branches:
      - master
    paths-ignore:
      - '.github/**'
      - 'LICENSE'
      - 'README.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      # - name: Deploy to Server
      #   uses: easingthemes/ssh-deploy@v3.0.1
      #   env:
      #     SSH_PRIVATE_KEY: ${{ secrets.ACCESS_TOKEN }}
      #     ARGS: "-avzr --delete"
      #     SOURCE: "docs/"
      #     REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
      #     REMOTE_USER: ${{ secrets.REMOTE_USER }}
      #     TARGET: ${{ secrets.TARGET }}
